export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED='FETCH_INGREDIENTS_FAILED';
export const PURCHASED_BURGER_SUCCESS='PURCHASED_BURGER_SUCCESS';

export const PURCHASED_BURGER_FAIL='PURCHASED_BURGER_FAIL';
export const PURCHASED_BURGER_START='PURCHASED_BURGER_START';
export const PURCHASED_INIT='PURCHASED_INIT';
export const FETCH_ORDERS_START='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS='FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL='FETCH_ORDERS_FAIL';
