export const FETCH_PROFILE_START='FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS='FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL='FETCH_PROFILE_FAIL';


export const AUTH_START='AUTH_START';
export const AUTH_SUCCESS='AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH='SET_AUTH_REDIRECT_PATH';


export const FETCH_ADDRESS_START='FETCH_ADDRESS_START';
export const FETCH_ADDRESS_SUCCESS='FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAIL='FETCH_ADDRESS_FAIL';
